/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PBL;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Shubham
 */
public class Branch extends javax.swing.JFrame {

    /**
     * Creates new form Form
     */
    
    public Branch() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
 regenerated by the Branch Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setTitle("Branch");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jButton1.setText("INSERT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Branch No.*:");

        jLabel3.setText("Branch Name:");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel4.setText("Branch Location:");

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jLabel5.setText("No. of Employees:");

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Lucida Calligraphy", 3, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Branch");

        jButton2.setText("UPDATE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("VIEW");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("DELETE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Branch No", "Branch Name", "Branch Location", "No. Of Employee"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                                    .addComponent(jTextField2)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField3)
                                    .addComponent(jTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE))))
                        .addGap(76, 76, 76))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       Connection c;
      Statement stmt;
        
        try
        {
            /*Class.forName("org.postgresql.Driver");
             Connection con=DriverManager.getConnection("jdbc:postgresql://localhost:5432/Shubham","postgres","root");
                 if(con!=null)
            {
                System.out.println("Connected");
            }*/
             Class.forName("org.postgresql.Driver");
                c = DriverManager.getConnection("jdbc:postgresql://localhost:5432/PBL",
            "postgres", "root");
         c.setAutoCommit(false);
//         System.out.println("Opened database successfully");
            
               
               Integer branch_number=Integer.parseInt(jTextField1.getText());
               String branch_name=jTextField2.getText();
               String branch_location=jTextField3.getText();
               Integer number_employee =Integer.parseInt(jTextField4.getText());
               //System.out.println("Display:"+ branch_number);
               
                stmt = c.createStatement();
         String sql = "INSERT INTO BRANCH VALUES ('"+(branch_number)+"', '"+(branch_name)+"', '"+(branch_location)+"','"+(number_employee)+"');";
        // stmt.execute(sql);
         //System.out.println("Hi:");
         if(jTextField1.getText().isEmpty()==true||jTextField2.getText().isEmpty()==true||jTextField3.getText().isEmpty()==true||jTextField4.getText().isEmpty()==true)
         {
                JOptionPane.showMessageDialog(this,"One or more fields are Empty Cannot Insert Data");
         }
         else
         {
         int rowsEffected=stmt.executeUpdate(sql);
             if(rowsEffected!=0)
                JOptionPane.showMessageDialog(this,"Data Inserted Succefully");
          stmt.close();
         }
         c.commit();
         c.close();
         
                
           /* 
              
            String sql =" insert into branch values(10,'aa','uu',6)";
            //String sql="  insert into branch values('branch_number','branch_name','branch_location','6')";
            st.execute(sql);
            //con.close();*/
        }
       catch(ClassNotFoundException | SQLException |NumberFormatException e)
        {
            String msg=e.getMessage();
            if(msg.contains("unique")==true)
            {
            JOptionPane.showMessageDialog(this,"Branch no. "+jTextField1.getText()+" already exists! Cannot Insert Data");
            }
            else if(msg.contains("input")==true)
            {
                JOptionPane.showMessageDialog(this,"Integer expected at Branch No. OR No. Of Employees");
            }
            else
            {
                JOptionPane.showMessageDialog(this,msg);
            }
        }
        

// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed
                                        
   
    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
        int row=model.getRowCount();
        if(row>0)
        {
             for(int i=0;i<row;i++)
            {
                 model.removeRow(0);
            }
        }
        String query="SELECT * from branch";
        try
        {
            Class.forName("org.postgresql.Driver");
            Connection con=DriverManager.getConnection("jdbc:postgresql://localhost:5432/PBL",
            "postgres", "root");
            Statement stmt=con.createStatement();
            ResultSet rs=stmt.executeQuery(query);
            while(rs.next())
            {
                String branch_number=rs.getString("branch_number");
                String branch_name=rs.getString("branch_name");
               String branch_location=rs.getString("branch_location");
               String number_employee=rs.getString("number_employee");
                //System.out.println(branch_number+ "|" + branch_name + "|"+ branch_location + "|" + number_employee);
                model.addRow(new Object[]{branch_number,branch_name,branch_location,number_employee});
            }
        }
        catch(ClassNotFoundException | SQLException | ArithmeticException | NumberFormatException e)
        {
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
    
         
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Connection c;
      Statement stmt;
        
        try
        {
            /*Class.forName("org.postgresql.Driver");
             Connection con=DriverManager.getConnection("jdbc:postgresql://localhost:5432/Shubham","postgres","root");
                 if(con!=null)
            {
                System.out.println("Connected");
            }*/
            
            
            
             Class.forName("org.postgresql.Driver");
                c = DriverManager.getConnection("jdbc:postgresql://localhost:5432/PBL",
            "postgres", "root");
         c.setAutoCommit(false);
         //System.out.println("Opened database successfully");
            
               
               Integer branch_number=Integer.parseInt(jTextField1.getText());
               String branch_name=jTextField2.getText();
               String branch_location=jTextField3.getText();
               Integer number_employee =Integer.parseInt(jTextField4.getText());
               //System.out.println("Display:"+ branch_number);
               
                stmt = c.createStatement();
                if(jTextField1.getText().isEmpty()==true||jTextField2.getText().isEmpty()==true||jTextField3.getText().isEmpty()==true||jTextField4.getText().isEmpty()==true)
                {
                    JOptionPane.showMessageDialog(this,"One or more fields are Empty Cannot Update Data");
                }
                else
                {
         String sql = "Update BRANCH Set branch_name='"+(branch_name)+"',branch_location='"+(branch_location)+"',"+
                  "number_employee='"+(number_employee)+"' where branch_number='"+(branch_number)+"';";
         int rowsEffected=stmt.executeUpdate(sql);
         if(rowsEffected==0)
                JOptionPane.showMessageDialog(this,"Record does not exist");
         else
             JOptionPane.showMessageDialog(this,"Record Updated");
         //System.out.println("Hi:");
          stmt.close();
                }
         c.commit();
         c.close();
                
           /* 
              
            String sql =" insert into branch values(10,'aa','uu',6)";
            //String sql="  insert into branch values('branch_number','branch_name','branch_location','6')";
            st.execute(sql);
            //con.close();*/
        }
       catch(ClassNotFoundException | SQLException |NumberFormatException e)
        {
            String msg=e.getMessage();
            /*if(msg.contains("unique")==true)
            {
            JOptionPane.showMessageDialog(this,"Branch no. "+jTextField1.getText()+" already exists! Cannot Insert Data");
            }
            else*/if(msg.contains("input")==true)
            {
                JOptionPane.showMessageDialog(this,"Integer expected at Branch No. OR No. Of Employees");
            }
            else
            {
                JOptionPane.showMessageDialog(this,msg);
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        Connection c;
      Statement stmt;
        
        try
        {
            /*Class.forName("org.postgresql.Driver");
             Connection con=DriverManager.getConnection("jdbc:postgresql://localhost:5432/Shubham","postgres","root");
                 if(con!=null)
            {
                System.out.println("Connected");
            }*/
            
            
            
             Class.forName("org.postgresql.Driver");
                c = DriverManager.getConnection("jdbc:postgresql://localhost:5432/PBL",
            "postgres", "root");
         c.setAutoCommit(false);
         //System.out.println("Opened database successfully");
            
               
               Integer branch_number=Integer.parseInt(jTextField1.getText());
               //String branch_name=jTextField2.getText();
               //String branch_location=jTextField3.getText();
               //Integer number_employee =Integer.parseInt(jTextField4.getText());
               //System.out.println("Display:"+ branch_number);
               
                stmt = c.createStatement();
         String sql = "DELETE FROM BRANCH where branch_number='"+(branch_number)+"';";
         int rowsEffected=stmt.executeUpdate(sql);
         if(rowsEffected==0)
                JOptionPane.showMessageDialog(this,"Record does not exist");
         else
             JOptionPane.showMessageDialog(this,"Record Deleted");
         //System.out.println("Hi:");
          stmt.close();
         c.commit();
         c.close();
                
           /* 
              
            String sql =" insert into branch values(10,'aa','uu',6)";
            //String sql="  insert into branch values('branch_number','branch_name','branch_location','6')";
            st.execute(sql);
            //con.close();*/
        }
       catch(ClassNotFoundException | SQLException | NumberFormatException | HeadlessException e)
        {
            String msg=e.getMessage();
            if(msg.contains("foreign")==true)
            {
                JOptionPane.showMessageDialog(this,"This Table is linked with Maintains Table Cannot Delete data");
            }
            else if(msg.contains("input")==true)
            {
                JOptionPane.showMessageDialog(this,"Integer expected at Branch no.");
            }
            else
           {
                JOptionPane.showMessageDialog(this,msg);
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Branch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Branch().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
