/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PBL;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Shubham
 */
public class Wrote extends javax.swing.JFrame {

    /**
     * Creates new form Wrote
     */
    public Wrote() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField2 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Book Code", "Author No", "Sequence No."
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setText("INSERT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setText("Sequence No:");

        jLabel6.setFont(new java.awt.Font("Lucida Calligraphy", 3, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Wrote");

        jButton3.setText("VIEW");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel2.setText("Book Code*:");

        jButton4.setText("DELETE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel3.setText("Author No*:");

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jButton2.setLabel("UPDATE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE))
                                .addGap(93, 93, 93)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField4)
                                    .addComponent(jTextField2)
                                    .addComponent(jTextField1))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Connection c;
        Statement stmt;

        try
        {
            /*Class.forName("org.postgresql.Driver");
            Connection con=DriverManager.getConnection("jdbc:postgresql://localhost:5432/Shubham","postgres","root");
            if(con!=null)
            {
                System.out.println("Connected");
            }*/

            Class.forName("org.postgresql.Driver");
            c = DriverManager.getConnection("jdbc:postgresql://localhost:5432/PBL",
                "postgres", "root");
            c.setAutoCommit(false);
           // System.out.println("Opened database successfully");

            String book_code=jTextField1.getText();
            Integer author_no=Integer.parseInt(jTextField2.getText());
            Integer sequence_number=Integer.parseInt(jTextField4.getText());
            //System.out.println("Display:"+ branch_number);

            stmt = c.createStatement();
            String sql = "INSERT INTO wrote VALUES ('"+(book_code)+"', '"+(author_no)+"', '"+(sequence_number)+"');";
            if(jTextField1.getText().isEmpty()==true||jTextField2.getText().isEmpty()==true||jTextField4.getText().isEmpty()==true)
         {
                JOptionPane.showMessageDialog(this,"One or more fields are Empty Cannot Insert Data");
         }
         else
         {
            int rowsEffected=stmt.executeUpdate(sql);
            if(rowsEffected!=0)
            JOptionPane.showMessageDialog(this,"Data Inserted Succefully");
            //System.out.println("Hi:");
           stmt.close();
         }
            c.commit();
            c.close();

            /*

            String sql =" insert into branch values(10,'aa','uu',6)";
            //String sql="  insert into branch values('branch_number','branch_name','branch_location','6')";
            st.execute(sql);
            //con.close();*/
        }
        catch(ClassNotFoundException | SQLException | NumberFormatException | HeadlessException e)
        {
            String msg=e.getMessage();
            if(msg.contains("unique")==true)
            {
            JOptionPane.showMessageDialog(this,"Book Code "+jTextField1.getText()+" and Author no. "+jTextField2.getText()+" already exists! Cannot Insert Data");
            }
            else if(msg.contains("input")==true)
            {
                JOptionPane.showMessageDialog(this,"Integer expected at Author No.Or Sequence no.");
            }
            else
            {
                JOptionPane.showMessageDialog(this,msg);
            }
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
        int row=model.getRowCount();
        if(row>0)
        {
            for(int i=0;i<row;i++)
            {
                model.removeRow(0);
            }
        }
        String query="SELECT * from wrote";
        try
        {
            Class.forName("org.postgresql.Driver");
            Connection con=DriverManager.getConnection("jdbc:postgresql://localhost:5432/PBL",
                "postgres", "root");
            Statement stmt=con.createStatement();
            ResultSet rs=stmt.executeQuery(query);
            while(rs.next())
            {
                String book_code=rs.getString("book_code");
                String author_no=rs.getString("author_no");
                String sequence_number=rs.getString("sequence_number");
                //System.out.println(book_code+ "|" + author_no + "|"+ sequence_number);
                model.addRow(new Object[]{book_code,author_no,sequence_number});
            }
        }
        catch(ClassNotFoundException | SQLException e)
        {
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        Connection c;
        Statement stmt;

        try
        {
            /*Class.forName("org.postgresql.Driver");
            Connection con=DriverManager.getConnection("jdbc:postgresql://localhost:5432/Shubham","postgres","root");
            if(con!=null)
            {
                System.out.println("Connected");
            }*/

            Class.forName("org.postgresql.Driver");
            c = DriverManager.getConnection("jdbc:postgresql://localhost:5432/PBL",
                "postgres", "root");
            c.setAutoCommit(false);
            //System.out.println("Opened database successfully");

            String book_code=jTextField1.getText();
            Integer author_no=Integer.parseInt(jTextField2.getText());
            //String sequence_number = jTextField4.getText();
            //System.out.println("Display:"+ branch_number);

            stmt = c.createStatement();
            String sql = "DELETE FROM wrote WHERE book_code='"+(book_code)+"' and author_no='"+(author_no)+"';";
            int rowsEffected=stmt.executeUpdate(sql);
            if(rowsEffected==0)
            JOptionPane.showMessageDialog(this,"Record does not exist");
            else
            JOptionPane.showMessageDialog(this,"Record Deleted");
           // System.out.println("Hi:");
           stmt.close();
            c.commit();
            c.close();

            /*

            String sql =" insert into branch values(10,'aa','uu',6)";
            //String sql="  insert into branch values('branch_number','branch_name','branch_location','6')";
            st.execute(sql);
            //con.close();*/
        }
        catch(ClassNotFoundException | SQLException | NumberFormatException | HeadlessException e)
        {
            String msg=e.getMessage();
            /*if(msg.contains("foreign")==true)
            {
                JOptionPane.showMessageDialog(this,"This Table is linked with Wrote Table Cannot Delete data");
            }
            else*/ if(msg.contains("input")==true)
            {
                JOptionPane.showMessageDialog(this,"One or more fields are Empty Cannot Delete Data");
            }
            else
            {
                JOptionPane.showMessageDialog(this,msg);
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Connection c;
        Statement stmt;

        try
        {
            /*Class.forName("org.postgresql.Driver");
            Connection con=DriverManager.getConnection("jdbc:postgresql://localhost:5432/Shubham","postgres","root");
            if(con!=null)
            {
                System.out.println("Connected");
            }*/

            Class.forName("org.postgresql.Driver");
            c = DriverManager.getConnection("jdbc:postgresql://localhost:5432/PBL",
                "postgres", "root");
            c.setAutoCommit(false);
            //System.out.println("Opened database successfully");

            String book_code=jTextField1.getText();
            Integer author_no=Integer.parseInt(jTextField2.getText());
            Integer sequence_number=Integer.parseInt(jTextField4.getText());
            //System.out.println("Display:"+ branch_number);

            stmt = c.createStatement();
            String sql = "UPDATE wrote SET sequence_number='"+(sequence_number)+"' WHERE author_no='"+(author_no)+"' and book_code='"+(book_code)+"';";
            if(jTextField1.getText().isEmpty()==true||jTextField2.getText().isEmpty()==true||jTextField4.getText().isEmpty()==true)
                {
                    JOptionPane.showMessageDialog(this,"One or more fields are Empty Cannot Update Data");
                }
                else
                {
            int rowsEffected=stmt.executeUpdate(sql);
            if(rowsEffected==0)
            JOptionPane.showMessageDialog(this,"Record does not exist");
            else
            JOptionPane.showMessageDialog(this,"Record Updated");
                }// System.out.println("Hi:");
           stmt.close();
            c.commit();
            c.close();

            /*

            String sql =" insert into branch values(10,'aa','uu',6)";
            //String sql="  insert into branch values('branch_number','branch_name','branch_location','6')";
            st.execute(sql);
            //con.close();*/
        }
        catch(ClassNotFoundException | SQLException |NumberFormatException e)
        {
            String msg=e.getMessage();
            /*if(msg.contains("unique")==true)
            {
            JOptionPane.showMessageDialog(this,"Branch no. "+jTextField1.getText()+" already exists! Cannot Insert Data");
            }
            else*/if(msg.contains("input")==true)
            {
                JOptionPane.showMessageDialog(this,"Integer expected at Author No. OR Sequence Number");
            }
            else
            {
                JOptionPane.showMessageDialog(this,msg);
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Wrote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Wrote().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
